config-version: 2
name: hubspot_source
require-dbt-version:
- '>=0.18.0'
- <0.19.0
vars:
  hubspot_source:
    company: '{{ source(''hubspot'',''company'') }}'
    company_property_history: '{{ source(''hubspot'',''company_property_history'')
      }}'
    contact: '{{ source(''hubspot'',''contact'') }}'
    contact_list: '{{ source(''hubspot'',''contact_list'') }}'
    contact_list_member: '{{ source(''hubspot'',''contact_list_member'') }}'
    contact_property_history: '{{ source(''hubspot'',''contact_property_history'')
      }}'
    deal: '{{ source(''hubspot'',''deal'') }}'
    deal_pipeline: '{{ source(''hubspot'',''deal_pipeline'') }}'
    deal_pipeline_stage: '{{ source(''hubspot'',''deal_pipeline_stage'') }}'
    deal_property_history: '{{ source(''hubspot'',''deal_property_history'') }}'
    email_campaign: '{{ source(''hubspot'',''email_campaign'') }}'
    email_event: '{{ source(''hubspot'',''email_event'') }}'
    email_event_bounce: '{{ source(''hubspot'',''email_event_bounce'') }}'
    email_event_click: '{{ source(''hubspot'',''email_event_click'') }}'
    email_event_deferred: '{{ source(''hubspot'',''email_event_deferred'') }}'
    email_event_delivered: '{{ source(''hubspot'',''email_event_delivered'') }}'
    email_event_dropped: '{{ source(''hubspot'',''email_event_dropped'') }}'
    email_event_forward: '{{ source(''hubspot'',''email_event_forward'') }}'
    email_event_open: '{{ source(''hubspot'',''email_event_open'') }}'
    email_event_print: '{{ source(''hubspot'',''email_event_print'') }}'
    email_event_sent: '{{ source(''hubspot'',''email_event_sent'') }}'
    email_event_spam_report: '{{ source(''hubspot'',''email_event_spam_report'') }}'
    email_event_status_change: '{{ source(''hubspot'',''email_event_status_change'')
      }}'
    engagement: '{{ source(''hubspot'',''engagement'') }}'
    engagement_call: '{{ source(''hubspot'',''engagement_call'') }}'
    engagement_company: '{{ source(''hubspot'',''engagement_company'') }}'
    engagement_contact: '{{ source(''hubspot'',''engagement_contact'') }}'
    engagement_deal: '{{ source(''hubspot'',''engagement_deal'') }}'
    engagement_email: '{{ source(''hubspot'',''engagement_email'') }}'
    engagement_meeting: '{{ source(''hubspot'',''engagement_meeting'') }}'
    engagement_note: '{{ source(''hubspot'',''engagement_note'') }}'
    engagement_task: '{{ source(''hubspot'',''engagement_task'') }}'
    owner: '{{ source(''hubspot'',''owner'') }}'
version: 1.0.0
